version: '3'
services:
  movies_db:
    image: mysql:5.7
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor2021
      MYSQL_DATABASE: MoviesDB
      MYSQL_USER: moviesUser
      MYSQL_PASSWORD: movies1234

  movies:
    tty: true
    image: docker.io/bitnami/laravel:8-debian-10
    environment:
      - DB_HOST=movies_db
      - DB_USERNAME=moviesUser
      - DB_DATABASE=MoviesDB
      - DB_PASSWORD=movies1234
    depends_on:
      - movies_db
    ports:
      - 3000:3000
    volumes:
      - ./:/app
