version: '3'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.2-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=moviesUser
      - MARIADB_DATABASE=MoviesDB
      - MARIADB_PASSWORD=movies1234

  movies:
    tty: true
    image: docker.io/bitnami/laravel:8-debian-10
    environment:
      - DB_HOST=movies_db
      - DB_USERNAME=moviesUser
      - DB_DATABASE=MoviesDB
      - DB_PASSWORD=movies1234
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
